language: php
php:
- '7.0'
- '7.1'
- '7.2'
- nightly

services:
- memcached

install:
- composer install

before_script:
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
- vendor/bin/phpunit
